petshop/urls.py
from django.contrib import admin
from django.urls import path, include
from base.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', inicio, name='inicio'),
    path('contato', contato, name='contato'),
    path('reserva/', include('reserva.urls', namespace='reserva')),
]

reserva/urls.py
from django.urls import path
from reserva.views import criar_reserva

app_name = 'reserva'

urlpatterns = [
    path('criar/', criar_reserva, name='criar_reserva')
]

base/models.py
from django.db import models

class Contato(models.Model):
    nome = models.CharField('Nome', max_length=50)
    email = models.EmailField('E-mail')
    mensagem = models.TextField('Mensagem', blank=True)
    criado_em = models.DateTimeField('data', auto_now_add=True)
    lido = models.BooleanField('Lido', default=False, blank=True)

    def __str__(self):
        return f'{self.nome} [{self.email}]'
    class Meta:
        verbose_name = 'Formulário de Contato'
        verbose_name_plural = 'Formulários de Contatos'
        ordering = ['-criado_em']

reserva/models.py
from django.db import models

class Reserva(models.Model):

    TAMANHO_OPCOES = {
        (0, 'Pequeno'),
        (1, 'Médio'),
        (2, 'Grande'),
    }

    TURNO_OPCOES = {
        ('manhã', 'Manhã'),
        ('tarde', 'Tarde'),
    }

    nome = models.CharField('Nome', max_length=50)
    email = models.EmailField('E-mail')
    nome_pet = models.CharField('Nome do Pet', max_length=80)
    data = models.DateField('Data', help_text='dd/mm/aaaa')
    turno = models.CharField('Turno', max_length=10, choices= TURNO_OPCOES)
    tamanho = models.IntegerField('Tamanho', choices= TAMANHO_OPCOES)
    observacoes = models.TextField('Observações', max_length=200, blank=True)
    criado_em = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.nome}: {self.data} - {self.turno}'
    
    class Meta:
        verbose_name = 'Reserva Banho'
        verbose_name_plural = 'Reservas de Banho'

base/forms.py
from django import forms
from base.models import Contato

class ContatoForm(forms.ModelForm):
    class Meta:
        model = Contato
        fields = ['nome', 'email', 'mensagem']

        widgets = {
            'nome': forms.TextInput(
                attrs={
                    'placeholder':'Informe o Nome Completo'
                }
                ),
            'email': forms.EmailInput(
                attrs={
                    'placeholder':'Informe o E-mail'
                }
            ),
            'mensagem': forms.Textarea(
                attrs={
                    'placeholder':'Escreva sua mensagem'
                }
            ),
        }

reserva/forms.py
from datetime import date
from django import forms
from reserva.models import Reserva

class ReservaForm(forms.ModelForm):

    def clean_data(self):
        data = self.cleaned_data.get('data')
        hoje = date.today()
        if data < hoje:
            raise forms.ValidationError('Não é possível realizar uma reserva para o passado!')
        return data
    
    def clean_turno(self):
        turno = self.cleaned_data.get('turno')
        data = self.cleaned_data.get('data')        
        reserva_turno = Reserva.objects.filter(data=data, turno=turno).count()
        if reserva_turno >= 2:
            raise forms.ValidationError(f'Numero maximo de reservas para o turno da {turno} excedidas')
        return turno

    class Meta:
        model = Reserva
        fields = ['nome', 'email', 'nome_pet', 'data', 'turno', 'tamanho', 'observacoes']

        widgets = {
            'nome': forms.TextInput(
                attrs = {
                    'placeholder': 'Insira o seu Nome'
                }
            ),
            'email': forms.TextInput(
                attrs = {
                    'placeholder': 'Insira o seu e-mail'
                }
            ),
            'nome_pet': forms.TextInput(
                attrs = {
                    'placeholder': 'Insira o nome do seu Pet'
                }
            ),
            'data': forms.DateInput(
                attrs = {
                    'type': 'date'
                }
            )
        }

base/views.py
from django.shortcuts import render
from base.forms import ContatoForm
from base.models import Contato

def inicio(request):
    return render(request, 'index.html')

def contato(request):
    sucesso = False
    form = ContatoForm(request.POST or None)
    if form.is_valid():
        form.save()
        sucesso = True
    contexto = {
        'sucesso': sucesso,
        'form': form,
    }
    
    return render(request, 'contato.html', contexto)

reserva/views.py
from django.shortcuts import render
from reserva.forms import ReservaForm
from reserva.models import Reserva

def criar_reserva(request):
    sucesso = False
    form_reserva = ReservaForm(request.POST or None)
    
    if form_reserva.is_valid():
        form_reserva.save()
        sucesso = True
    contexto = {
        'sucesso': sucesso,
        'form': form_reserva,
        'reserva': Reserva(),
    }  

    return render(request, 'reserva.html', contexto)

base/templates/contato.html
{% extends 'index.html'%}
{% load bootstrap5 %}
{% block title %}Atividade M6S2 - Pagina Contato{% endblock %}
{% block banner %}
  <h1 class="display-4 fst-italic">Contato</h1>
  <p class="lead my-2">Preencha os campos abaixo.</p>
{% endblock %}
{% block conteudo %}
  {% if sucesso %}
    <p class="alert alert-success">Mensagem Encaminhada com Sucesso!</p>
  {% else %}
    <form action="" method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}    
      {% buttons %}
          <button type="submit" class="btn btn-primary">Enviar</button>
      {% endbuttons %}    
    </form>
  {% endif %}
{% endblock %}

base/templates/index.html
<!doctype html>
{% load bootstrap5 %}
<html lang="pt-br">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">
  <title>{%block title%}Atividade M6S2 - Pagina Inicial Petshop{%endblock%}</title>

  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>
  <!-- Custom styles for this template -->
  <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">
  <!-- Custom styles for this template -->
  
</head>
<body>
  <div class="container">
    {%block header%}
    <header class="border-bottom lh-1 py-3">
      <div class="row flex-nowrap justify-content-between align-items-center">
        <div class="col-4 pt-1">
          <a class="text-dark" href="{% url 'inicio' %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-house" viewBox="0 0 16 16">
              <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.707 1.5ZM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5 5 5Z"/>
            </svg>
          </a>          
        </div>
        <div class="col-4 text-center">
          <a class="text-dark text-decoration-none" href="{% url 'inicio' %}">
            <h1 class="blog-header-logo text-body-emphasis text-decoration-none">PET SHOP</h1>
          </a>
        </div>
        <div class="col-4 d-flex justify-content-end align-items-center">
          <a class="btn btn-sm btn-outline-secondary" href="{% url 'reserva:criar_reserva' %}">RESERVE AQUI</a>
        </div>
      </div>
    </header>
    <div class="nav-scroller py-1 mb-3 border-bottom">
      <nav class="nav nav-underline justify-content-between">
        <a class="nav-item nav-link link-body-emphasis active" href="#">Pagina1</a>
        <a class="nav-item nav-link link-body-emphasis" href="#">Pagina2</a>
        <a class="nav-item nav-link link-body-emphasis" href="#">Pagina3</a>
        <a class="nav-item nav-link link-body-emphasis" href="{%url 'contato'%}">Contato</a>
        
      </nav>
    </div>
    {%endblock%}
  </div>

  <main class="container">
      <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
        <div class="row mb-2">
          <div class="col-md-6 px-0">
            {% block banner %}
            <h1 class="display-4 fst-italic">Petshop</h1>
            <p class="lead my-2">RESERVE HORARIO PARA O BANHO DO SEU PET.</p>
            {% endblock %}
          </div>
        </div>
      </div>

    
    <div class="container justify-content-center">
      {% block conteudo %}
      <div class="row g-3"></div>
        <div class="py-5 my-5 border border-5 text-center">
          <p>Conteúdo da Pagina Inicial Aqui</p>
        </div>
      </div>
      {% endblock %}
    </div>
    

  </main>
  <footer class="py-5 text-center text-body-secondary bg-body-tertiary">
    <p>Atividade de Django para o curso de Desenvolvedor em Python Completo da <a href="https://promo.ultima.school/python/">Ultima School</a>
    <p>
      <a href="{% url 'inicio' %}">Voltar a home</a>
    </p>
  </footer>
</body>
</html>

reserva/templates/reserva.html
{% extends 'index.html'%}
{% load bootstrap5 %}
{%block title%}Atividade M6S2 - Pagina Contato{%endblock%}
{% block banner %}
  <h3 class="display-6 fst-italic">Reserve aqui o banho do seu PET</h3>
  <p class="lead my-2">Preencha os campos abaixo.</p>
{%endblock%}
{% block conteudo %}
  {% if sucesso %}
    <p class="alert alert-success">Reserva realizada com Sucesso!</p>
  {% else %}
    <form action="" method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}    
      {% buttons %}
          <button type="submit" class="btn btn-primary">Enviar</button>
      {% endbuttons %}    
    </form>
  {% endif %}
{% endblock %}